export const ALL_MOVIE_CONSTATNS = {
  LOAD_MOVIES_ALL_REQUEST: "LOAD_MOVIES_ALL_REQUEST",
  LOAD_MOVIES_ALL_SUCCESS: "LOAD_MOVIES_ALL_SUCCESS",
  LOADED_MOVIES_ALL_FALURE: "LOADED_MOVIES_ALL_FALURE",
};
export const REQUIRED_MOVIE = {
  REQUIRED_MOVIE_REQUEST: "REQUIRED_MOVIE_REQUEST",
  REQUIRED_MOVIE_SUCCESS: "REQUIRED_MOVIE_SUCCESS",
  REQUIRED_MOVIE_FALURE: "REQUIRED_MOVIE_FALURE",
};
export const OPERATION_CONSTATNS = {
  LOAD_OPERATION_REQUEST: "LOAD_OPERATION_REQUEST",
  LOAD_OPERATION_SUCCESS: "LOAD_OPERATION_SUCCESS",
  LOAD_OPERATION_FAILURE: "LOAD_OPERATION_FAILURE",
};
export const FILTER_CONSTATNS = {
  FILTER_CONSTATNS_REQUEST: "FILTER_CONSTATNS_REQUEST",
  FILTER_CONSTATNS_SUCCESS: "FILTER_CONSTATNS_SUCCESS",
  FILTER_CONSTATNS_FAILURE: "FILTER_CONSTATNS_FAILURE",
};
export const HIGHVIEWED_CONSTATNS = {
  HIGHVIEWED_CONSTATNS_REQUEST: "HIGHVIEWED_CONSTATNS_REQUEST",
  HIGHVIEWED_CONSTATNS_SUCCESS: "HIGHVIEWED_CONSTATNS_SUCCESS",
  HIGHVIEWED_CONSTATNS_FAILURE: "HIGHVIEWED_CONSTATNS_FAILURE",
};
export const RECENT_OR_POPULAR_CONSTANTS = {
  RECENT_OR_POPULAR_CONSTANTS_REQUEST: "RECENT_OR_POPULAR_CONSTANTS_REQUEST",
  RECENT_OR_POPULAR_CONSTANTS_SUCCESS: "RECENT_OR_POPULAR_CONSTANTS_SUCCESS",
  RECENT_OR_POPULAR_CONSTANTS_FAILURE: "RECENT_OR_POPULAR_CONSTANTS_FAILURE",
};

// export const HINDI_MOVIE_CONSTANTS = {
//   LOAD_HINDI_MOVIES_REQUEST: "LOAD_HINDI_MOVIES_REQUEST",
//   LOAD_HINDI_MOVIES_SUCCESS: "LOAD_HINDI_MOVIES_SUCCESS",
//   LOAD_HINDI_MOVIES_FAILURE: "LOAD_HINDI_MOVIES_FAILURE",
// };
// export const ENGLISH_MOVIE_CONSTANTS = {
//   LOAD_ENGLISH_MOVIES_REQUEST: "LOAD_ENGLISH_MOVIES_REQUEST",
//   LOAD_ENGLISH_MOVIES_SUCCESS: "LOAD_ENGLISH_MOVIES_SUCCESS",
//   LOAD_ENGLISH_MOVIES_FAILURE: "LOAD_ENGLISH_MOVIES_FAILURE",
// };
// export const OPERATION_CONSTATNS = {
//   LOAD_OPERATION_REQUEST: "LOAD_OPERATION_REQUEST",
//   LOAD_OPERATION_SUCCESS: "LOAD_OPERATION_SUCCESS",
//   LOAD_OPERATION_FAILURE: "LOAD_OPERATION_FAILURE",
// };
